#+title: fake_fastgithub 开发记录
#+author: ysouyno
#+options: ^:nil

* 从零开始 <2024-05-30 周四>

~FastGithub~ 是一个非常优秀的工具，每天都在用，同时对于域有特殊的效果。我想将它再完善一下，主要适应自自己的使用方式。但目前有两个难点：

1. 不了解 ~csharp~ ，很难下手。
2. 不了解网络概念，比如 ~CDN~ ， ~反向代理~ 等等。

从昨天的调查发现， ~FastGithub~ 使用的是 ~ASP.NET Core~ 工程类型，并使用 ~YARP~ 实现反向代理，昨天已经写了两个小 ~demo~ 大概了解了这两个知识点，所以今天就直接动手了，先创建一个 ~ASP.NET Core Empty~ 工程，然后替换 ~Program.cs~ 中的默认代码如下：

#+begin_src csharp
  namespace fake_fastgithub
  {
      class Program
      {
          public static void Main(string[] args)
          {
              Console.WriteLine("fake_fastgithub");
              var options = new WebApplicationOptions
              {
                  Args = args,
              };
              CreateWebApplication(options).Run(/*singleton: true*/);
          }

          private static WebApplication CreateWebApplication(WebApplicationOptions options)
          {
              var builder = WebApplication.CreateBuilder(options);
              var app = builder.Build();
              app.MapGet("/", () => "Hello World!");

              return app;
          }
      }
  }
#+end_src

** ~ServiceExtensions~ 是怎么建立联系的？ <2024-05-30 周四>

原工程中的 ~singleton~ 在新工程中无法编译通过，发现 ~singleton~ 是在 ~ServiceExtensions~ 类中似乎重写了 ~Run~ 函数，但是我没有 ~ServiceExtensions~ 是怎么建立上联系的？

取消 ~TODO~ ：这 ~ServiceExtensions~ 类看来就是为了注册 ~windows~ 服务的，有违的我初衷，所以就不追这个细节了。

** 添加 ~Serilog~ 功能 <2024-05-30 周四>

使用 ~NuGet~ 安装：

1. 安装 ~Serilog.Sinks.Console~ 和 ~Serilog.Sinks.File~ 日志功能。
2. 为了用上 ~UseSerilog~ 函数，你还得安装 ~Serilog.Extensions.Hosting~ 。
3. 为了用上 ~ReadFrom.Configuration~ ，你还得安装 ~Serilog.Settings.Configuration~ 。

** 添加 ~kestrel~ 扩展 <2024-05-30 周四>

#+begin_quote
Class Library

A project for creating a class library that targets .NET or .NET Standard
#+end_quote

1. 创建一个 ~Class Library~ 类型的工程 ~fake_fastgithub.HttpServer~ ， ~vs~ 中有众多的 ~Class Library~ ，请选择这个（见上）。
2. 创建 ~KestrelServerExtensions~ 类，并新增 ~NoLimit()~ 方法。
