#+title: fake_fastgithub 开发记录
#+author: ysouyno
#+options: ^:nil

* 从零开始 <2024-05-30 周四>

~FastGithub~ 是一个非常优秀的工具，每天都在用，同时对于域有特殊的效果。我想将它再完善一下，主要适应自自己的使用方式。但目前有两个难点：

+ 不了解 ~csharp~ ，很难下手。
+ 不了解网络概念，比如 ~CDN~ ， ~反向代理~ 等等。

从昨天的调查发现， ~FastGithub~ 使用的是 ~ASP.NET Core~ 工程类型，并使用 ~YARP~ 实现反向代理，昨天已经写了两个小 ~demo~ 大概了解了这两个知识点，所以今天就直接动手了，先创建一个 ~ASP.NET Core Empty~ 工程，然后替换 ~Program.cs~ 中的默认代码如下：

#+begin_src csharp
  namespace fake_fastgithub
  {
      class Program
      {
          public static void Main(string[] args)
          {
              Console.WriteLine("fake_fastgithub");
              var options = new WebApplicationOptions
              {
                  Args = args,
              };
              CreateWebApplication(options).Run(/*singleton: true*/);
          }

          private static WebApplication CreateWebApplication(WebApplicationOptions options)
          {
              var builder = WebApplication.CreateBuilder(options);
              var app = builder.Build();
              app.MapGet("/", () => "Hello World!");

              return app;
          }
      }
  }
#+end_src

** ~ServiceExtensions~ 是怎么建立联系的？ <2024-05-30 周四>

原工程中的 ~singleton~ 在新工程中无法编译通过，发现 ~singleton~ 是在 ~ServiceExtensions~ 类中似乎重写了 ~Run~ 函数，但是我没有 ~ServiceExtensions~ 是怎么建立上联系的？

取消 ~TODO~ ：这 ~ServiceExtensions~ 类看来就是为了注册 ~windows~ 服务的，有违的我初衷，所以就不追这个细节了。

** 添加 ~Serilog~ 功能 <2024-05-30 周四>

使用 ~NuGet~ 安装：

+ 安装 ~Serilog.Sinks.Console~ 和 ~Serilog.Sinks.File~ 日志功能。
+ 为了用上 ~UseSerilog~ 函数，你还得安装 ~Serilog.Extensions.Hosting~ 。
+ 为了用上 ~ReadFrom.Configuration~ ，你还得安装 ~Serilog.Settings.Configuration~ 。

** 添加 ~kestrel~ 扩展 <2024-05-30 周四>

#+begin_quote
Class Library

A project for creating a class library that targets .NET or .NET Standard
#+end_quote

+ 创建一个 ~Class Library~ 类型的工程 ~fake_fastgithub.HttpServer~ ， ~vs~ 中有众多的 ~Class Library~ ，请选择这个（见上）。
+ 创建 ~KestrelServerExtensions~ 类，并新增 ~NoLimit()~ 方法。
+ 右键新建的工程，选择 ~Edit Project File~ 菜单，添加如下，这样在 ~Dependencies~ 的 ~Frameworks~ 中就可以看到 ~Microsoft.AspNetCore.App~ 了， ~KestrelServerOptions~ 类型也就不报错了。

#+begin_src xml
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
#+end_src

+ 然后将自动生成的命名空间从 ~fake_fastgithub.HttpServer~ 修改为 ~fake_fastgithub~ ，这样 ~fake_fastgithub.HttpServer~ 就编译成功了。

但是此时 ~fake_fastgithub~ 却编译失败：

#+begin_quote
error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute
#+end_quote

** 更改目录结构 <2024-05-30 周四>

~CS0579~ 这个错误可能跟目录结构有关：

+ 创建一个空的解决方案 ~Blank Solution~ ，让 ~vs~ 来管理各子工程。
+ 同时这样的话，各个子工程生成的 ~exe~ 或 ~dll~ 都在同一个目录下。

经过这样修改后，现在编译错误就正常多了：

#+begin_quote
error CS1061: 'KestrelServerOptions' does not contain a definition for 'NoLimit'
#+end_quote

** 解决 ~CS1061~ 这个错误 <2024-05-30 周四>

在 ~fake_fastgithub~ 项目中设置 ~Dependencies~ 的关联工程 ~fake_fastgithub.HttpServer~ 即可。

目前所有代码编译都成功！

** 新增 ~fake_fastgithub.Configuration~ 工程

尝试添加 ~ListenHttpsReverseProxy~ 函数，要用到 ~GlobalListener.HttpsPort~ ，它属于 ~fake_fastgithub.Configuration~ 工程，添加了该工程及 ~GlobalListener~ 类后，目前编译报错：

#+begin_quote
error CS0103: The name 'GlobalListener' does not exist in the current context
#+end_quote

暂时先用 ~443~ 代替 ~GlobalListener.HttpsPort~ 让编译通过。
